import type React from "react"
import type { Metadata } from "next"
import { Baskervville, Plus_Jakarta_Sans, Courier_Prime } from "next/font/google"
import { Suspense } from "react"
import { Analytics } from "@vercel/analytics/react"
import "./globals.css"

const baskervville = Baskervville({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
})

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
})

const courierPrime = Courier_Prime({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
})

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://neothink.io"

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "Neothink+ | Admin of Neothink",
  description:
    "Admin of the extraordinary values provided by Mark Hamilton, Wallace Hamilton, the Hamilton Family, and the Neothink Society. Supporting Ascenders, Neothinkers, Immortals, and Superachievers.",
  alternates: {
    canonical: siteUrl,
  },
  keywords: [
    "Neothink",
    "Mark Hamilton",
    "Neothink Society",
    "Ascenders",
    "Neothinkers",
    "Immortals",
    "Superachievers",
    "Neo-Tech",
    "integrated thinking",
    "self-leadership",
    "value creation",
  ],
  authors: [{ name: "Neothink Society" }],
  openGraph: {
    title: "Neothink+ | Admin of Neothink",
    description:
      "Admin of the extraordinary values provided by Mark Hamilton, Wallace Hamilton, the Hamilton Family, and the Neothink Society.",
    url: "https://neothink.io",
    siteName: "Neothink+",
    type: "website",
    // Dynamic OG image generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Neothink+ | Admin of Neothink",
    description:
      "Admin of the extraordinary values provided by Mark Hamilton, Wallace Hamilton, the Hamilton Family, and the Neothink Society.",
    // Dynamic Twitter image generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://markhamilton.co" />
        <link rel="preconnect" href="https://neothink.com" />
        <link rel="preconnect" href="https://community.neothink.io" />
        <link rel="dns-prefetch" href="https://markhamilton.co" />
        <link rel="dns-prefetch" href="https://neothink.com" />
        <link rel="dns-prefetch" href="https://community.neothink.io" />
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#FFD700" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#FFD700" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "Person",
                  "@id": "https://neothink.io/#frank-wallace",
                  name: "Dr. Frank R. Wallace",
                  description: "Founder of Neo-Tech (1980) and the integrated thinking philosophy",
                  birthDate: "1932",
                  deathDate: "2006",
                },
                {
                  "@type": "Person",
                  "@id": "https://markhamilton.co/#person",
                  name: "Mark Hamilton",
                  url: "https://markhamilton.co",
                  description: "Founder of Neothink Society, continuing the Neo-Tech legacy",
                  memberOf: {
                    "@id": "https://neothink.com/#organization",
                  },
                },
                {
                  "@type": "Organization",
                  "@id": "https://neothink.com/#organization",
                  name: "Neothink Society",
                  url: "https://neothink.com",
                  foundingDate: "2007",
                  founder: {
                    "@id": "https://markhamilton.co/#person",
                  },
                  description: "Continuing the Neo-Tech legacy through integrated thinking, self-leadership, and value creation.",
                },
                {
                  "@type": "WebApplication",
                  "@id": "https://neothink.io/#webapp",
                  name: "Neothink+",
                  url: "https://neothink.io",
                  applicationCategory: "BusinessApplication",
                  description: "Admin of the extraordinary values provided by Mark Hamilton, Wallace Hamilton, the Hamilton Family, and the Neothink Society. Supporting Ascenders, Neothinkers, Immortals, and Superachievers.",
                  slogan: "Prosper Happily Forever",
                  about: [
                    { "@id": "https://markhamilton.co/#person" },
                    { "@id": "https://neothink.com/#organization" },
                  ],
                  offers: [
                    {
                      "@type": "Offer",
                      name: "Ascenders Path",
                      description: "LIVE - Prosperity through value creation. Access Ascension, FLOW, and Ascenders community.",
                      category: "Prosperity",
                    },
                    {
                      "@type": "Offer",
                      name: "Neothinkers Path",
                      description: "LOVE - Happiness through integrated thinking. Access Neothink, Mark Hamilton content, and Neothinkers community.",
                      category: "Happiness",
                    },
                    {
                      "@type": "Offer",
                      name: "Immortals Path",
                      description: "LIFE - Longevity through self-leadership. Access Immortalis, Project Life, and Immortals community.",
                      category: "Longevity",
                    },
                    {
                      "@type": "Offer",
                      name: "Superachievers Path",
                      description: "LUCK - Complete access to all paths and communities for maximum achievement.",
                      category: "Achievement",
                    },
                  ],
                },
              ],
            }),
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                document.documentElement.classList.toggle('dark', theme === 'dark');
              })();
            `,
          }}
        />
      </head>
      <body
        className={`font-sans ${baskervville.variable} ${plusJakartaSans.variable} ${courierPrime.variable} antialiased`}
      >
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-primary focus:px-4 focus:py-2 focus:text-primary-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
        >
          Skip to main content
        </a>
        <Suspense fallback={null}>{children}</Suspense>
        <Analytics />
      </body>
    </html>
  )
}
